"use client"

import { useEffect, useState } from "react"
import { motion } from "framer-motion"
import { ExternalLink } from "lucide-react"
import { useTheme } from "@/components/theme-provider"
import type { ContributionData, ContributionLevel } from "@/lib/github-contributions"

interface GitHubActivityProps {
  contributions: ContributionData
  username: string
}

const SNAKE_BASE =
  "https://raw.githubusercontent.com/Arpanjeetsingh/my_portfolio/output"

// Theme-matched palettes for the static heatmap fallback. The snake SVG
// generated by the workflow uses the exact same color stops (solid hex
// equivalents of these rgba blends over var(--bg-card) = #221a14).
const HEATMAP_COLORS = {
  arthur: [
    "rgba(201, 169, 97, 0.1)",
    "rgba(201, 169, 97, 0.3)",
    "rgba(201, 169, 97, 0.5)",
    "rgba(201, 169, 97, 0.7)",
    "rgba(201, 169, 97, 1)",
  ],
  atie: [
    "rgba(22, 27, 34, 1)",
    "rgba(14, 68, 41, 1)",
    "rgba(0, 109, 50, 1)",
    "rgba(38, 166, 65, 1)",
    "rgba(57, 211, 83, 1)",
  ],
} as const

export function GitHubActivity({ contributions, username }: GitHubActivityProps) {
  const { theme } = useTheme()
  const [snakeStatus, setSnakeStatus] = useState<"loading" | "loaded" | "error">(
    "loading"
  )

  const palette = HEATMAP_COLORS[theme]
  const getColor = (level: ContributionLevel) => palette[level]
  const profileUrl = `https://github.com/${username}`

  const snakeSrc =
    theme === "arthur"
      ? `${SNAKE_BASE}/github-contribution-grid-snake.svg`
      : `${SNAKE_BASE}/github-contribution-grid-snake-dark.svg`

  // Reset to loading whenever the theme (and therefore snake src) switches, so
  // the heatmap fallback shows again while the new variant is downloading.
  useEffect(() => {
    setSnakeStatus("loading")
  }, [snakeSrc])

  const showSnake = snakeStatus === "loaded"

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ duration: 0.7, delay: 0.1 }}
      className="theme-card p-6 h-full"
    >
      {/* Header */}
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-3">
          <svg
            className="h-5 w-5"
            viewBox="0 0 24 24"
            fill="currentColor"
            style={{ color: "var(--text-primary)" }}
          >
            <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
          </svg>
          <span
            className="font-display text-lg font-semibold"
            style={{ color: "var(--text-primary)" }}
          >
            GitHub Activity
          </span>
          <span
            className="theme-badge px-2 py-0.5 text-xs font-medium"
            style={{
              backgroundColor:
                theme === "arthur"
                  ? "rgba(201, 169, 97, 0.2)"
                  : "rgba(34, 197, 94, 0.2)",
              color: theme === "arthur" ? "var(--accent)" : "#22c55e",
            }}
          >
            ↗ {contributions.total}
          </span>
        </div>
        <a
          href={profileUrl}
          target="_blank"
          rel="noopener noreferrer"
          className="theme-button flex items-center gap-2 px-3 py-1.5 text-sm font-medium border transition-colors hover:opacity-80"
          style={{
            borderColor: "var(--border-faint)",
            color: "var(--text-primary)",
          }}
        >
          View Profile
          <ExternalLink className="h-3 w-3" />
        </a>
      </div>

      {/* Contribution count */}
      <p className="mb-4 text-sm" style={{ color: "var(--text-muted)" }}>
        {contributions.total} contributions in the last year
      </p>

      {/*
        Single visualization slot:
        - Snake SVG (preferred): includes the contribution dots already, colored
          to match the heatmap palette via params in .github/workflows/snake.yml.
        - Static heatmap fallback: visible only while the snake is still loading
          or failed to load (e.g. the workflow hasn't published the output branch
          yet on a fresh deploy).
      */}
      <div className="overflow-x-auto">
        {/*
          The img is always mounted (no display:none) so the browser actually
          fetches it. With display:none + loading=lazy, browsers skip the
          fetch entirely and onLoad never fires.

          The wrapper enforces aspect-ratio 880/150 with overflow:hidden so
          the bottom ~22% of the SVG (Platane/snk's built-in "stack" progress
          bar at y=144 and the empty padding below it) is cropped out. The
          contribution grid sits at y=2-110 in viewBox coords, well within the
          kept top portion.
        */}
        <div
          className="overflow-hidden"
          style={{ aspectRatio: "880 / 150" }}
        >
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            key={snakeSrc}
            src={snakeSrc}
            alt={`${contributions.total} GitHub contributions in the last year, animated by a snake`}
            className="w-full h-auto block"
            onLoad={() => setSnakeStatus("loaded")}
            onError={() => setSnakeStatus("error")}
          />
        </div>

        {!showSnake && (
          <>
            <div className="flex gap-[3px] pb-2">
              {contributions.weeks.map((week, weekIndex) => (
                <div key={weekIndex} className="flex flex-col gap-[3px]">
                  {week.map((day, dayIndex) => (
                    <div
                      key={dayIndex}
                      className="h-[10px] w-[10px] rounded-sm"
                      style={{ backgroundColor: getColor(day.level) }}
                      title={
                        day.date
                          ? `${day.count} contribution${day.count === 1 ? "" : "s"} on ${day.date}`
                          : undefined
                      }
                    />
                  ))}
                </div>
              ))}
            </div>

            <div className="flex items-center justify-end gap-2">
              <span className="text-xs" style={{ color: "var(--text-muted)" }}>
                Less
              </span>
              <div className="flex gap-1">
                {([0, 1, 2, 3, 4] as ContributionLevel[]).map((level) => (
                  <div
                    key={level}
                    className="h-[10px] w-[10px] rounded-sm"
                    style={{ backgroundColor: getColor(level) }}
                  />
                ))}
              </div>
              <span className="text-xs" style={{ color: "var(--text-muted)" }}>
                More
              </span>
            </div>
          </>
        )}
      </div>
    </motion.div>
  )
}
